name: Release
on:
    release:
        types: [published]

jobs:

    
    build-windows-installer:
        name: Create Windows Installer
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              uses: msys2/setup-msys2@v2
              with:
                  install: >-
                      mingw-w64-x86_64-toolchain
                      mingw-w64-x86_64-ninja
                      mingw-w64-x86_64-SDL2
                      mingw-w64-x86_64-nsis
                      mingw-w64-x86_64-openssl
                  msystem: mingw64
                  release: false

            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                  version: "5.15.2"
                  host: "windows"
                  target: "desktop"
                  arch: "win64_mingw81"
                  dir: "${{ github.workspace }}/qt/"
                  install-deps: "true"

            - name: Configure CMake
              run: cmake -DCMAKE_BUILD_TYPE=Debug  -B '${{ github.workspace }}'/build
              env:
                  CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}

            - name: Build Installer
              run: cmake --build '${{ github.workspace }}'/build --parallel 8

            - name: Upload binaries to release
              uses: AButler/upload-release-assets@v2.0
              with:
                  files: build/antimicrox*.exe
                  repo-token: ${{ github.token }}
